version: 2.1

orbs:
  blackduck: dwave/orb-blackduck@dev:dev


workflows:
  version: 2.1
  test:
    jobs:
      - blackduck/blackduck
      # - coverage-gcc
      # - coverage-gcc-4.8
      # - coverage-clang
      # - coverage-osx
      # - test-3.9
      # - test-3.8
      # - test-3.7
      # - test-3.6
      # - test-3.5
      # - test-osx-3.9
      # - test-osx-3.8
      # - test-osx-3.7
      # - test-osx-3.6
      # - test-osx-3.5
